# Generated by Django 3.0.2 on 2020-01-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('owner_id', models.IntegerField(default=0)),
                ('sharer_id', models.CharField(max_length=200)),
                ('driver_id', models.IntegerField(default=0)),
                ('arrival_datetime', models.DateTimeField()),
                ('destination', models.CharField(max_length=100)),
                ('can_share', models.BooleanField()),
                ('current_person_total', models.IntegerField(default=0)),
                ('other_info', models.CharField(max_length=200)),
                ('required_vehicle_type', models.CharField(max_length=200)),
            ],
        ),
    ]
