# Generated by Django 3.0.2 on 2020-01-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0002_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.IntegerField(default=0),
        ),
    ]
