# Generated by Django 3.0.2 on 2020-01-29 01:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0002_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=9),
        ),
    ]
