# Generated by Django 3.0.2 on 2020-01-29 02:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0003_auto_20200129_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='current_person_total',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='person_number_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer_id_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=9),
        ),
    ]
