# Generated by Django 3.0.2 on 2020-01-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0004_driver_user_id'),
        ('uper', '0005_auto_20200129_0259'),
    ]

    operations = [
    ]
