# Generated by Django 3.0.2 on 2020-01-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0006_merge_20200129_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
