# Generated by Django 3.0.2 on 2020-01-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0007_delete_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('license_number', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('other_info', models.CharField(max_length=80)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
