# Generated by Django 3.0.2 on 2020-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0008_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='total_person_number',
            field=models.IntegerField(default=0),
        ),
    ]
