# Generated by Django 3.0.2 on 2020-02-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0009_ride_total_person_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='driver_id',
            new_name='total_rider_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='person_number_list',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer_id_list',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='total_person_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='uper.User'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uper.Driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='can_share',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Personal_ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_time', models.DateTimeField()),
                ('identity', models.CharField(max_length=20)),
                ('party_person_number', models.IntegerField(default=0)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uper.Ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uper.User')),
            ],
        ),
    ]
