# Generated by Django 3.0.2 on 2020-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0012_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
