# Generated by Django 3.0.2 on 2020-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uper', '0013_auto_20200207_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20),
        ),
    ]
